//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pract_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cloth()
        {
            this.Models = new HashSet<Models>();
            this.More = new HashSet<More>();
        }
    
        public int ID_Cloth { get; set; }
        public int ID_Color { get; set; }
        public int ID_Resistance { get; set; }
        public int ID_Density { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Density Density { get; set; }
        public virtual Resistance Resistance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Models> Models { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<More> More { get; set; }
    }
}
