//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pract_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Repair_requests = new HashSet<Repair_requests>();
        }
    
        public int ID_Equipment { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int Number { get; set; }
        public System.DateTime Date_of_purchase { get; set; }
        public int Year_of_release { get; set; }
        public string Speed { get; set; }
        public string Stitch_Length { get; set; }
        public string Stitch_Widths { get; set; }
        public string Size_of_the_loop_strip { get; set; }
        public bool Connecting_to_a_computer { get; set; }
        public bool Automatic_winding { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair_requests> Repair_requests { get; set; }
    }
}
