//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pract_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class More
    {
        public int ID_More { get; set; }
        public int ID_Models { get; set; }
        public int ID_Cloth { get; set; }
        public int ID_Accessories { get; set; }
    
        public virtual Accessories Accessories { get; set; }
        public virtual Cloth Cloth { get; set; }
        public virtual Models Models { get; set; }
    }
}
