//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pract_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public int ID_Queue { get; set; }
        public int ID_Orders { get; set; }
        public int ID_Status_order { get; set; }
        public string Urgency { get; set; }
    
        public virtual Ordedrs Ordedrs { get; set; }
        public virtual Status_order Status_order { get; set; }
    }
}
